# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='recommand',
            field=models.TextField(default=''),
        ),
    ]
