# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylang', '0005_auto_20170601_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tmp_answer',
            name='cur_user',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tmp_answer',
            name='cur_date',
            field=models.IntegerField(default=0),
        ),
    ]
