# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylang', '0010_voca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='level',
            new_name='like_dislike_voca',
        ),
        migrations.AddField(
            model_name='user_info',
            name='listening_level',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user_info',
            name='readding_level',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user_info',
            name='vocabulary_level',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='voca',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voca',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
