# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylang', '0011_auto_20170608_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='readding_level',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='vocabulary_level',
            field=models.TextField(default='0'),
        ),
    ]
