# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylang', '0012_auto_20170624_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='message_box',
            field=models.TextField(default=''),
        ),
    ]
