# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 06:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('hashed_url', models.CharField(max_length=255, null=True)),
                ('caption', models.TextField()),
                ('title', models.CharField(default='Nop!', max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(default='1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur', models.URLField(default='')),
            ],
        ),
    ]
