# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylang', '0003_tmp_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmp_answer',
            name='cur_date',
            field=models.IntegerField(default=0),
        ),
    ]
