# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 05:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylang', '0006_auto_20170602_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='user',
            new_name='cur_user',
        ),
    ]
