# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylang', '0008_auto_20170603_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='level',
            field=models.TextField(default=''),
        ),
    ]
