# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylang', '0009_user_info_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='voca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign', models.TextField(default='')),
                ('korean', models.TextField(default='')),
            ],
        ),
    ]
